export class EnvConfig {
  // static GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID';
  // static GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET';
  // static GOOGLE_CALLBACK_URL = 'GOOGLE_CALLBACK_URL';

  static JWT_ACCESS_SECRET = 'JWT_ACCESS_SECRET';
  static JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET';

  static RESEND_API_KEY = 'RESEND_API_KEY';

  static CLOUDINARY_CLOUD_NAME = 'CLOUDINARY_CLOUD_NAME';
  static CLOUDINARY_API_KEY = 'CLOUDINARY_API_KEY';
  static CLOUDINARY_API_SECRET = 'CLOUDINARY_API_SECRET';
}
